name: DebugBuild
on:
  push:
    branches:
      - master
  
env:
  # リポジトリのルートディレクトリを基点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: project/MyGame.sln
  # サブプロジェクトへの正確なパス
  ASSET_GEN_PROJ: project/Tools/AssetGenerator/AssetGenerator.vcxproj
  # Visual Studio の構成(debug / Release)
  CONFIGURATION: Debug
  
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          # 1. まず AssetGenerator を個別にビルド（これで .exe を確実に作る）
      - name: Build AssetGenerator
        run: |
          msbuild ${{env.ASSET_GEN_PROJ}} /p:Platform=x64 /p:Configuration=${{env.CONFIGURATION}}
          # 2. 次にソリューション全体をビルド
      - name: Build MyGame
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
